#!/usr/bin/env bash
# cron_setup.sh — Schedule the Botetourt tracker scraper daily on Ubuntu (Digital Ocean)
# Run once as the deploy user: bash cron_setup.sh
set -euo pipefail

# ── Configuration ──────────────────────────────────────────────────────────
REPO_DIR="${REPO_DIR:-/opt/botetourt-tracker}"
PYTHON="${PYTHON:-python3}"
LOG_FILE="${LOG_FILE:-/var/log/botetourt-tracker/scraper.log}"
CRON_HOUR="${CRON_HOUR:-6}"    # run at 6 AM UTC daily
CRON_MIN="${CRON_MIN:-30}"

# ── Colors ─────────────────────────────────────────────────────────────────
GREEN="\033[0;32m"; YELLOW="\033[1;33m"; RED="\033[0;31m"; RESET="\033[0m"
info()  { echo -e "${GREEN}[info]${RESET}  $*"; }
warn()  { echo -e "${YELLOW}[warn]${RESET}  $*"; }
error() { echo -e "${RED}[error]${RESET} $*" >&2; exit 1; }

# ── Preflight ──────────────────────────────────────────────────────────────
info "Checking prerequisites…"
command -v "$PYTHON" >/dev/null 2>&1  || error "python3 not found. Install: sudo apt install python3"
command -v crontab   >/dev/null 2>&1  || error "crontab not found. Install: sudo apt install cron"

[[ -d "$REPO_DIR" ]]                  || error "Repo dir not found: $REPO_DIR  (set REPO_DIR= env var)"
[[ -f "$REPO_DIR/scraper.py" ]]       || error "scraper.py not found in $REPO_DIR"

# ── Log directory ──────────────────────────────────────────────────────────
LOG_DIR="$(dirname "$LOG_FILE")"
if [[ ! -d "$LOG_DIR" ]]; then
  info "Creating log directory: $LOG_DIR"
  sudo mkdir -p "$LOG_DIR"
  sudo chown "$(whoami)" "$LOG_DIR"
fi

# ── Install Python deps (stdlib only, nothing to install) ──────────────────
info "scraper.py uses stdlib only — no pip install needed."

# ── Write wrapper script ───────────────────────────────────────────────────
WRAPPER="/usr/local/bin/botetourt-scrape"
info "Writing wrapper script to $WRAPPER"
sudo tee "$WRAPPER" > /dev/null <<WRAPPER_EOF
#!/usr/bin/env bash
# Auto-generated by cron_setup.sh — do not edit manually
set -euo pipefail
cd "$REPO_DIR"
"$PYTHON" scraper.py >> "$LOG_FILE" 2>&1

# If the repo is a git repo, commit and push updated data files
if git -C "$REPO_DIR" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  git -C "$REPO_DIR" add data.json changelog.json 2>/dev/null || true
  if ! git -C "$REPO_DIR" diff --cached --quiet; then
    git -C "$REPO_DIR" commit -m "chore: auto-update data [$(date -u +%Y-%m-%dT%H:%M:%SZ)]" \
      --author="Botetourt Bot <bot@botetourt-tracker>" >> "$LOG_FILE" 2>&1
    git -C "$REPO_DIR" push >> "$LOG_FILE" 2>&1 \
      && echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] Pushed updated data to GitHub Pages" >> "$LOG_FILE"
  else
    echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] No data changes to commit" >> "$LOG_FILE"
  fi
fi
WRAPPER_EOF
sudo chmod +x "$WRAPPER"

# ── Install cron entry ─────────────────────────────────────────────────────
CRON_LINE="${CRON_MIN} ${CRON_HOUR} * * * $WRAPPER"
MARKER="# botetourt-tracker"

info "Installing cron entry: ${CRON_LINE}"
(
  crontab -l 2>/dev/null | grep -v "$MARKER" | grep -v botetourt-scrape
  echo "$MARKER"
  echo "$CRON_LINE"
) | crontab -

# ── Log rotation ───────────────────────────────────────────────────────────
LOGROTATE_CONF="/etc/logrotate.d/botetourt-tracker"
if [[ ! -f "$LOGROTATE_CONF" ]]; then
  info "Setting up log rotation at $LOGROTATE_CONF"
  sudo tee "$LOGROTATE_CONF" > /dev/null <<LOGROTATE_EOF
$LOG_FILE {
    weekly
    rotate 8
    compress
    missingok
    notifempty
    create 0640 $(whoami) $(whoami)
}
LOGROTATE_EOF
fi

# ── Summary ────────────────────────────────────────────────────────────────
echo ""
info "Setup complete!"
echo ""
echo "  Cron schedule : ${CRON_MIN} ${CRON_HOUR} * * *  (daily at ${CRON_HOUR}:$(printf '%02d' "$CRON_MIN") UTC)"
echo "  Repo dir      : $REPO_DIR"
echo "  Log file      : $LOG_FILE"
echo "  Wrapper       : $WRAPPER"
echo ""
echo "  Run manually  : $WRAPPER"
echo "  View logs     : tail -f $LOG_FILE"
echo "  View cron     : crontab -l"
echo ""
warn "Ensure the deploy user has SSH push access to the GitHub repo for auto-commit to work."
warn "Test with: bash $WRAPPER && tail -20 $LOG_FILE"
